name: iiedmulti
recipe: drupal7
config:
  php: '8.1'
  drush: '8.4.12'
  webroot: docroot
proxy:
  appserver:
    - biocultural.lndo.site
  mailhog:
    - mail.iiedmulti.lndo.site
services:
  database:
    type: mariadb:10.11
    creds:
      user: database
      password: database
      database: database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
tooling:
  drush:
    service: appserver
    cmd:
      - 'drush --root=/app/docroot --uri=biocultural.lndo.site'
